use_frameworks!

target 'MQTTClientSwift_Example' do
  pod 'MQTTClientSwift', :path => '../'

  target 'MQTTClientSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
